-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SneakySnake_bit_NeighborhoodMap_bit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    DNA_read_val : IN STD_LOGIC_VECTOR (255 downto 0);
    DNA_ref_val : IN STD_LOGIC_VECTOR (255 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (127 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (127 downto 0) );
end;


architecture behav of SneakySnake_bit_NeighborhoodMap_bit is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv256_lc_3 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv256_lc_4 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv256_lc_5 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv256_lc_6 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv256_lc_7 : STD_LOGIC_VECTOR (255 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv32_7A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111010";
    constant ap_const_lv8_55 : STD_LOGIC_VECTOR (7 downto 0) := "01010101";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv10_155 : STD_LOGIC_VECTOR (9 downto 0) := "0101010101";
    constant ap_const_lv32_76 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal DNA_1_fu_224_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_1_reg_774 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_2_fu_237_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_2_reg_779 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_3_fu_250_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_3_reg_784 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_6_fu_263_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_6_reg_789 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_7_fu_276_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_7_reg_794 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_8_fu_289_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_8_reg_799 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_4_fu_310_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_4_reg_804 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_5_fu_331_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_5_reg_809 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_9_fu_352_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_9_reg_814 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_10_fu_373_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_10_reg_819 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_11_fu_394_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal DNA_11_reg_824 : STD_LOGIC_VECTOR (255 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_DNA_nsh_write_assign_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_DNA_nsh_write_assign_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_storemerge953_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_storemerge953_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_storemerge852_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_storemerge852_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_storemerge751_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_storemerge751_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_storemerge650_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_storemerge650_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_storemerge549_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_storemerge549_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_storemerge448_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_storemerge448_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_storemerge347_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_storemerge347_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_storemerge246_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_storemerge246_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_storemerge145_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_storemerge145_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_done : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_idle : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_ready : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_storemerge44_out : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_storemerge44_out_ap_vld : STD_LOGIC;
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg : STD_LOGIC := '0';
    signal grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal shl_ln398_fu_231_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln417_fu_244_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln436_fu_257_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln460_fu_270_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal shl_ln486_fu_283_p2 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln_fu_296_p4 : STD_LOGIC_VECTOR (253 downto 0);
    signal zext_ln514_fu_306_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln1_fu_317_p4 : STD_LOGIC_VECTOR (251 downto 0);
    signal zext_ln532_fu_327_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln2_fu_338_p4 : STD_LOGIC_VECTOR (249 downto 0);
    signal zext_ln554_fu_348_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln3_fu_359_p4 : STD_LOGIC_VECTOR (247 downto 0);
    signal zext_ln578_fu_369_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal lshr_ln4_fu_380_p4 : STD_LOGIC_VECTOR (245 downto 0);
    signal zext_ln605_fu_390_p1 : STD_LOGIC_VECTOR (255 downto 0);
    signal tmp_s_fu_493_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_15_fu_516_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_16_fu_526_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_17_fu_549_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_18_fu_559_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_19_fu_569_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_20_fu_592_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_21_fu_602_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_22_fu_612_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_23_fu_622_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shl_one_write_assign_fu_407_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shl_two_write_assign_fu_420_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shl_three_write_assign_fu_435_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shl_four_write_assign_fu_450_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shl_five_write_assign_fu_465_p5 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shr_one_write_assign_fu_480_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shr_two_write_assign_fu_503_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shr_three_write_assign_fu_536_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shr_four_write_assign_fu_579_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal DNA_shr_five_write_assign_fu_632_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_1 : IN STD_LOGIC_VECTOR (255 downto 0);
        DNA_nsh_write_assign_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        DNA_nsh_write_assign_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_2 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge953_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge953_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_3 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge852_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge852_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_6 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge751_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge751_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_7 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge650_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge650_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_8 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge549_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge549_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_4 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge448_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge448_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_5 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge347_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge347_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_9 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge246_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge246_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_10 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge145_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge145_out_ap_vld : OUT STD_LOGIC );
    end component;


    component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        DNA_11 : IN STD_LOGIC_VECTOR (255 downto 0);
        storemerge44_out : OUT STD_LOGIC_VECTOR (127 downto 0);
        storemerge44_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_ready,
        DNA_1 => DNA_1_reg_774,
        DNA_nsh_write_assign_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_DNA_nsh_write_assign_out,
        DNA_nsh_write_assign_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_DNA_nsh_write_assign_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_ready,
        DNA_2 => DNA_2_reg_779,
        storemerge953_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_storemerge953_out,
        storemerge953_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_storemerge953_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_ready,
        DNA_3 => DNA_3_reg_784,
        storemerge852_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_storemerge852_out,
        storemerge852_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_storemerge852_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_ready,
        DNA_6 => DNA_6_reg_789,
        storemerge751_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_storemerge751_out,
        storemerge751_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_storemerge751_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_ready,
        DNA_7 => DNA_7_reg_794,
        storemerge650_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_storemerge650_out,
        storemerge650_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_storemerge650_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_ready,
        DNA_8 => DNA_8_reg_799,
        storemerge549_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_storemerge549_out,
        storemerge549_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_storemerge549_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_ready,
        DNA_4 => DNA_4_reg_804,
        storemerge448_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_storemerge448_out,
        storemerge448_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_storemerge448_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_ready,
        DNA_5 => DNA_5_reg_809,
        storemerge347_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_storemerge347_out,
        storemerge347_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_storemerge347_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_ready,
        DNA_9 => DNA_9_reg_814,
        storemerge246_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_storemerge246_out,
        storemerge246_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_storemerge246_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_ready,
        DNA_10 => DNA_10_reg_819,
        storemerge145_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_storemerge145_out,
        storemerge145_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_storemerge145_out_ap_vld);

    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218 : component SneakySnake_bit_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start,
        ap_done => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_done,
        ap_idle => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_idle,
        ap_ready => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_ready,
        DNA_11 => DNA_11_reg_824,
        storemerge44_out => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_storemerge44_out,
        storemerge44_out_ap_vld => grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_storemerge44_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_ready = ap_const_logic_1)) then 
                    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                DNA_10_reg_819 <= DNA_10_fu_373_p2;
                DNA_11_reg_824 <= DNA_11_fu_394_p2;
                DNA_1_reg_774 <= DNA_1_fu_224_p2;
                DNA_2_reg_779 <= DNA_2_fu_237_p2;
                DNA_3_reg_784 <= DNA_3_fu_250_p2;
                DNA_4_reg_804 <= DNA_4_fu_310_p2;
                DNA_5_reg_809 <= DNA_5_fu_331_p2;
                DNA_6_reg_789 <= DNA_6_fu_263_p2;
                DNA_7_reg_794 <= DNA_7_fu_276_p2;
                DNA_8_reg_799 <= DNA_8_fu_289_p2;
                DNA_9_reg_814 <= DNA_9_fu_352_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    DNA_10_fu_373_p2 <= (zext_ln578_fu_369_p1 xor DNA_ref_val);
    DNA_11_fu_394_p2 <= (zext_ln605_fu_390_p1 xor DNA_ref_val);
    DNA_1_fu_224_p2 <= (DNA_ref_val xor DNA_read_val);
    DNA_2_fu_237_p2 <= (shl_ln398_fu_231_p2 xor DNA_ref_val);
    DNA_3_fu_250_p2 <= (shl_ln417_fu_244_p2 xor DNA_ref_val);
    DNA_4_fu_310_p2 <= (zext_ln514_fu_306_p1 xor DNA_ref_val);
    DNA_5_fu_331_p2 <= (zext_ln532_fu_327_p1 xor DNA_ref_val);
    DNA_6_fu_263_p2 <= (shl_ln436_fu_257_p2 xor DNA_ref_val);
    DNA_7_fu_276_p2 <= (shl_ln460_fu_270_p2 xor DNA_ref_val);
    DNA_8_fu_289_p2 <= (shl_ln486_fu_283_p2 xor DNA_ref_val);
    DNA_9_fu_352_p2 <= (zext_ln554_fu_348_p1 xor DNA_ref_val);
    DNA_shl_five_write_assign_fu_465_p5 <= (ap_const_lv10_155 & grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_storemerge549_out(117 downto 0));
    DNA_shl_four_write_assign_fu_450_p5 <= (ap_const_lv8_55 & grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_storemerge650_out(119 downto 0));
    DNA_shl_one_write_assign_fu_407_p4 <= (ap_const_lv2_1 & grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_storemerge953_out(125 downto 0));
    DNA_shl_three_write_assign_fu_435_p5 <= (ap_const_lv6_15 & grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_storemerge751_out(121 downto 0));
    DNA_shl_two_write_assign_fu_420_p5 <= (ap_const_lv4_5 & grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_storemerge852_out(123 downto 0));
    DNA_shr_five_write_assign_fu_632_p4 <= (tmp_23_fu_622_p4(127 downto 6) & ap_const_lv2_1 & tmp_23_fu_622_p4(3 downto 0));
    DNA_shr_four_write_assign_fu_579_p4 <= (tmp_19_fu_569_p4(127 downto 5) & ap_const_lv2_1 & tmp_19_fu_569_p4(2 downto 0));
    DNA_shr_one_write_assign_fu_480_p4 <= (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_storemerge448_out(127 downto 2) & ap_const_lv2_1);
    DNA_shr_three_write_assign_fu_536_p4 <= (tmp_16_fu_526_p4(127 downto 4) & ap_const_lv2_1 & tmp_16_fu_526_p4(1 downto 0));
    DNA_shr_two_write_assign_fu_503_p4 <= (tmp_s_fu_493_p4(127 downto 3) & ap_const_lv2_1 & tmp_s_fu_493_p4(0 downto 0));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_done, grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_done = ap_const_logic_0) or (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_DNA_nsh_write_assign_out;
    ap_return_1 <= DNA_shl_one_write_assign_fu_407_p4;
    ap_return_10 <= DNA_shr_five_write_assign_fu_632_p4;
    ap_return_2 <= DNA_shl_two_write_assign_fu_420_p5;
    ap_return_3 <= DNA_shl_three_write_assign_fu_435_p5;
    ap_return_4 <= DNA_shl_four_write_assign_fu_450_p5;
    ap_return_5 <= DNA_shl_five_write_assign_fu_465_p5;
    ap_return_6 <= DNA_shr_one_write_assign_fu_480_p4;
    ap_return_7 <= DNA_shr_two_write_assign_fu_503_p4;
    ap_return_8 <= DNA_shr_three_write_assign_fu_536_p4;
    ap_return_9 <= DNA_shr_four_write_assign_fu_579_p4;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_380_1_fu_158_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_400_2_fu_164_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_419_3_fu_170_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_438_4_fu_176_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_462_5_fu_182_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_488_6_fu_188_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_516_7_fu_194_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_ap_start_reg;
    grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start <= grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_ap_start_reg;
    lshr_ln1_fu_317_p4 <= DNA_read_val(255 downto 4);
    lshr_ln2_fu_338_p4 <= DNA_read_val(255 downto 6);
    lshr_ln3_fu_359_p4 <= DNA_read_val(255 downto 8);
    lshr_ln4_fu_380_p4 <= DNA_read_val(255 downto 10);
    lshr_ln_fu_296_p4 <= DNA_read_val(255 downto 2);
    shl_ln398_fu_231_p2 <= std_logic_vector(shift_left(unsigned(DNA_read_val),to_integer(unsigned('0' & ap_const_lv256_lc_3(31-1 downto 0)))));
    shl_ln417_fu_244_p2 <= std_logic_vector(shift_left(unsigned(DNA_read_val),to_integer(unsigned('0' & ap_const_lv256_lc_4(31-1 downto 0)))));
    shl_ln436_fu_257_p2 <= std_logic_vector(shift_left(unsigned(DNA_read_val),to_integer(unsigned('0' & ap_const_lv256_lc_5(31-1 downto 0)))));
    shl_ln460_fu_270_p2 <= std_logic_vector(shift_left(unsigned(DNA_read_val),to_integer(unsigned('0' & ap_const_lv256_lc_6(31-1 downto 0)))));
    shl_ln486_fu_283_p2 <= std_logic_vector(shift_left(unsigned(DNA_read_val),to_integer(unsigned('0' & ap_const_lv256_lc_7(31-1 downto 0)))));
    tmp_15_fu_516_p4 <= (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_556_9_fu_206_storemerge246_out(127 downto 2) & ap_const_lv2_1);
    tmp_16_fu_526_p4 <= (tmp_15_fu_516_p4(127 downto 3) & ap_const_lv2_1 & tmp_15_fu_516_p4(0 downto 0));
    tmp_17_fu_549_p4 <= (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_580_10_fu_212_storemerge145_out(127 downto 2) & ap_const_lv2_1);
    tmp_18_fu_559_p4 <= (tmp_17_fu_549_p4(127 downto 3) & ap_const_lv2_1 & tmp_17_fu_549_p4(0 downto 0));
    tmp_19_fu_569_p4 <= (tmp_18_fu_559_p4(127 downto 4) & ap_const_lv2_1 & tmp_18_fu_559_p4(1 downto 0));
    tmp_20_fu_592_p4 <= (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_607_11_fu_218_storemerge44_out(127 downto 2) & ap_const_lv2_1);
    tmp_21_fu_602_p4 <= (tmp_20_fu_592_p4(127 downto 3) & ap_const_lv2_1 & tmp_20_fu_592_p4(0 downto 0));
    tmp_22_fu_612_p4 <= (tmp_21_fu_602_p4(127 downto 4) & ap_const_lv2_1 & tmp_21_fu_602_p4(1 downto 0));
    tmp_23_fu_622_p4 <= (tmp_22_fu_612_p4(127 downto 5) & ap_const_lv2_1 & tmp_22_fu_612_p4(2 downto 0));
    tmp_s_fu_493_p4 <= (grp_NeighborhoodMap_bit_Pipeline_VITIS_LOOP_534_8_fu_200_storemerge347_out(127 downto 2) & ap_const_lv2_1);
    zext_ln514_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_296_p4),256));
    zext_ln532_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_317_p4),256));
    zext_ln554_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_338_p4),256));
    zext_ln578_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln3_fu_359_p4),256));
    zext_ln605_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln4_fu_380_p4),256));
end behav;
